
package App;

//import App.Config;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
//import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
//import javax.swing.table.TableColumnModel;


public class Daftar_Penjualan extends javax.swing.JFrame {

    public Daftar_Penjualan() {
        initComponents();
        setLocationRelativeTo(null);
        Tampilkan_Data();
//        configureTableResizable();
    }

    private void Tampilkan_Data() {
        DefaultTableModel model = new DefaultTableModel();
        // Set column headers
        model.setColumnIdentifiers(new Object[]{"ID Penjualan", "Tanggal", "Total", "Cash", "Kembalian"});
        tbl_penjualan.setModel(model);

        // Setup currency formatting for Indonesian Rupiah
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);

        try {
            java.sql.Connection conn = Config.configDB();
            // Modified SQL query to get only sales data without id_akun
            String sql = "SELECT id, tanggal, total, cash, kembali FROM penjualan ORDER BY tanggal DESC";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                // Format currency values
                String totalFormatted = kursIndonesia.format(rs.getDouble("total"));
                String cashFormatted = kursIndonesia.format(rs.getDouble("cash"));
                String kembaliFormatted = kursIndonesia.format(rs.getDouble("kembali"));

                // Get values from result set
                int id = rs.getInt("id");
                String tanggal = rs.getString("tanggal");

                // Add row to table model with formatted currency values
                model.addRow(new Object[]{
                    id,
                    tanggal,
                    totalFormatted,
                    cashFormatted,
                    kembaliFormatted
                });
            }

            // Auto-resize columns to fit content
            for (int i = 0; i < tbl_penjualan.getColumnCount(); i++) {
                tbl_penjualan.getColumnModel().getColumn(i).setPreferredWidth(150);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

//    private void configureTableResizable() {
//        // Nonaktifkan resize otomatis
//        tbl_penjualan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
//
//        // Aktifkan resize manual kolom
//        tbl_penjualan.getTableHeader().setResizingAllowed(true);
//
//        // Atur lebar awal kolom (sesuaikan angka sesuai kebutuhan)
//        TableColumnModel columnModel = tbl_penjualan.getColumnModel();
//        columnModel.getColumn(0).setPreferredWidth(50);   // ID
//        columnModel.getColumn(1).setPreferredWidth(120);  // nama
//        columnModel.getColumn(2).setPreferredWidth(114);  // jenis
//        columnModel.getColumn(3).setPreferredWidth(200);   // jumlah
//        columnModel.getColumn(4).setPreferredWidth(120);  // no_telp
////        columnModel.getColumn(5).setPreferredWidth(120);  // no_telp
//
//        // Pastikan JScrollPane tidak menimpa pengaturan tabel
//        JScrollPane scrollPane = (JScrollPane) tbl_penjualan.getParent().getParent();
//        scrollPane.setViewportView(tbl_penjualan);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_penjualan = new javax.swing.JTable();
        tbl_penjualan.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

                label.setBackground(new Color(0x35AEFF));
                label.setForeground(Color.WHITE);
                label.setOpaque(true);
                return label;
            }
        });
        btn_cetak = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "JENIS", "TOTAL", "TANGGAL", "CASH", "KEMBALI"
            }
        ));
        tbl_penjualan.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jScrollPane1.setViewportView(tbl_penjualan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 730, 310));

        btn_cetak.setContentAreaFilled(false);
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 290, 40));

        btn_kembali.setContentAreaFilled(false);
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 240, 40));

        background.setIcon(new FlatSVGIcon("UI_Svg/daftarPenjualan.svg"));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 30, 800, 410));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/login.gif"))); // NOI18N
        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        Daftar halamandaftar = new Daftar();
        halamandaftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        // Get the selected row from the table
        int selectedRow = tbl_penjualan.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih penjualan yang akan dicetak terlebih dahulu!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get the ID Penjualan from selected row
        int idPenjualan = (int) tbl_penjualan.getValueAt(selectedRow, 0);

        try {
            // Buat koneksi ke database
            java.sql.Connection con = Config.configDB();

            // Load file report
            String reportPath = "src/Nota/notaDidiexs.jasper"; // Sesuaikan path
            JasperReport jasperReport = (JasperReport) JRLoader.loadObjectFromFile(reportPath);

            // Buat parameter ke report
            Map<String, Object> param = new HashMap<>();
            param.put("idpenjualan", idPenjualan);

            // Isi laporan dengan data
            JasperPrint print = JasperFillManager.fillReport(jasperReport, param, con);

            // Tampilkan laporan
            JasperViewer.viewReport(print, false);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this,
                    "Gagal memuat file report: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Gagal mencetak nota: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    

    }//GEN-LAST:event_btn_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Daftar_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Daftar_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Daftar_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Daftar_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Daftar_Penjualan().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_penjualan;
    // End of variables declaration//GEN-END:variables
}
