
package App;


import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class Daftar_Ikanmati extends javax.swing.JFrame {


    public Daftar_Ikanmati() {
        initComponents();
        setLocationRelativeTo(null);
        Tampilkan_Data();
        configureTableResizable();
    }

    
    private void Tampilkan_Data() {
        try {
            // Koneksi ke database
            java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/didiexs", "root", "");

            // Query JOIN untuk mengambil data dari catatan_ikan_mati dengan jenis ikan dari tabel products
            String sql = "SELECT c.id, p.jenis AS jenis_ikan, c.jumlah, c.tanggal, c.keterangan "
                    + "FROM catatan_ikan_mati c "
                    + "JOIN products p ON c.id_products = p.id";

            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            // Buat model untuk JTable
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Jenis Ikan");
            model.addColumn("Jumlah");
            model.addColumn("Tanggal");
            model.addColumn("Keterangan");

            // Looping data dari database ke JTable
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("jenis_ikan"), // Diambil dari tabel products
                    rs.getInt("jumlah"),
                    rs.getString("tanggal"),
                    rs.getString("keterangan")
                });
            }

            // Set model ke JTable
            tbl_ikanmati.setModel(model);

            // Tutup koneksi
            rs.close();
            pst.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
        }
    }
    
    
    private void configureTableResizable() {
    // Nonaktifkan resize otomatis
    tbl_ikanmati.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    
    // Aktifkan resize manual kolom
    tbl_ikanmati.getTableHeader().setResizingAllowed(true);
    
    // Atur lebar awal kolom (sesuaikan angka sesuai kebutuhan)
    TableColumnModel columnModel = tbl_ikanmati.getColumnModel();
    columnModel.getColumn(0).setPreferredWidth(50);   // ID
    columnModel.getColumn(1).setPreferredWidth(120);  // nama
    columnModel.getColumn(2).setPreferredWidth(80);  // jenis
    columnModel.getColumn(3).setPreferredWidth(200);   // jumlah
    columnModel.getColumn(4).setPreferredWidth(274);  // no_telp
    
    // Pastikan JScrollPane tidak menimpa pengaturan tabel
    JScrollPane scrollPane = (JScrollPane) tbl_ikanmati.getParent().getParent();
    scrollPane.setViewportView(tbl_ikanmati);
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ikanmati = new javax.swing.JTable();
        tbl_ikanmati.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

                label.setBackground(new Color(0x35AEFF));
                label.setForeground(Color.WHITE);
                label.setOpaque(true);
                return label;
            }
        });
        btn_kembali = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_ikanmati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_ikanmati.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jScrollPane1.setViewportView(tbl_ikanmati);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 730, 310));

        btn_kembali.setContentAreaFilled(false);
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 180, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/daftar ikan mati.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 30, 800, 420));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/login.gif"))); // NOI18N
        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        Daftar halamandaftar = new Daftar();
        halamandaftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_Ikanmati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_Ikanmati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_Ikanmati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_Ikanmati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_Ikanmati().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ikanmati;
    // End of variables declaration//GEN-END:variables
}
