package App;

import java.awt.Color;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class Daftar_PO extends javax.swing.JFrame {

    /**
     * Creates new form Daftar_PO
     */
    public Daftar_PO() {
        initComponents();
        setLocationRelativeTo(null);
        Tampilkan_Data();
        configureTableResizable();
    }

    private void Tampilkan_Data() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"ID", "Atas Nama", "Jenis Ikan", "Jumlah", "No Telepon", "Tgl Pemesanan", "Keterangan", "Status"});
        tbl_po.setModel(model);

        try {
            java.sql.Connection conn = Config.configDB();
            String sql = "SELECT * FROM preorder";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("atas_nama");
                String jenis = rs.getString("jenis_ikan");
                int jumlah = rs.getInt("jumlah");
                String nomer = rs.getString("no_telp");
                String tanggal = rs.getString("tanggal_pemesanan");
                String keterangan = rs.getString("keterangan");
                String status = rs.getString("status");

                model.addRow(new Object[]{id, nama, jenis, jumlah, nomer, tanggal, keterangan, status,});
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void configureTableResizable() {
        // Nonaktifkan resize otomatis
        tbl_po.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        // Aktifkan resize manual kolom
        tbl_po.getTableHeader().setResizingAllowed(true);

        // Atur lebar awal kolom (sesuaikan angka sesuai kebutuhan)
        TableColumnModel columnModel = tbl_po.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(44);   // ID
        columnModel.getColumn(1).setPreferredWidth(70);  // nama
        columnModel.getColumn(2).setPreferredWidth(100);  // jenis
        columnModel.getColumn(3).setPreferredWidth(50);   // jumlah
        columnModel.getColumn(4).setPreferredWidth(100);  // no_telp
        columnModel.getColumn(5).setPreferredWidth(150);  // tanggal
        columnModel.getColumn(6).setPreferredWidth(150);  // keterangan
        columnModel.getColumn(7).setPreferredWidth(60);  // keterangan

        // Pastikan JScrollPane tidak menimpa pengaturan tabel
        JScrollPane scrollPane = (JScrollPane) tbl_po.getParent().getParent();
        scrollPane.setViewportView(tbl_po);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_po = new javax.swing.JTable();
        tbl_po.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

                label.setBackground(new Color(0x35AEFF));
                label.setForeground(Color.WHITE);
                label.setOpaque(true);
                return label;
            }
        });
        btn_selesai = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_po.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_po.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jScrollPane1.setViewportView(tbl_po);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 730, 310));

        btn_selesai.setContentAreaFilled(false);
        btn_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selesaiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 180, 30));

        btn_kembali.setContentAreaFilled(false);
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 180, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Png/daftarPO (1).png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 30, 800, 410));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/login.gif"))); // NOI18N
        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        Daftar halamandaftar = new Daftar();
        halamandaftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selesaiActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_po.getSelectedRow();
    System.out.println("Selected row: " + selectedRow);

    if (selectedRow != -1) {
        int idPreorder = Integer.parseInt(tbl_po.getValueAt(selectedRow, 0).toString());
        System.out.println("ID yang dipilih: " + idPreorder);

        try {
            java.sql.Connection conn = Config.configDB();
            String sql = "UPDATE preorder SET status = 'selesai' WHERE id = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, idPreorder);

            int rows = stmt.executeUpdate();
            System.out.println("Baris yang diperbarui: " + rows);

            if (rows > 0) {
                // Anda bisa update tampilan manual:
                tbl_po.setValueAt("selesai", selectedRow, 7);

                // atau lebih baik: refresh data
//                loadTable(); // Pastikan Anda punya fungsi ini

                JOptionPane.showMessageDialog(null, "Status berhasil diubah ke selesai.");
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada data yang diperbarui. Periksa ID.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal memperbarui status.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih salah satu baris terlebih dahulu.");
    }
    }//GEN-LAST:event_btn_selesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_PO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_selesai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_po;
    // End of variables declaration//GEN-END:variables
}
