/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author admin
 */
public class Daftar extends javax.swing.JFrame {

    /**
     * Creates new form Daftar
     */
    public Daftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_d_penjualan = new javax.swing.JButton();
        btn_d_preorder = new javax.swing.JButton();
        btn_d_ikanmati = new javax.swing.JButton();
        btn_d_pembelian = new javax.swing.JButton();
        btn_product = new javax.swing.JButton();
        btn_penjualan = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_preorder = new javax.swing.JButton();
        btn_daftar = new javax.swing.JButton();
        btn_catatan = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bar_bawah = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_d_penjualan.setContentAreaFilled(false);
        btn_d_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_d_penjualanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_d_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 220, 150));

        btn_d_preorder.setContentAreaFilled(false);
        btn_d_preorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_d_preorderActionPerformed(evt);
            }
        });
        getContentPane().add(btn_d_preorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 220, 150));

        btn_d_ikanmati.setContentAreaFilled(false);
        btn_d_ikanmati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_d_ikanmatiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_d_ikanmati, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 220, 150));

        btn_d_pembelian.setContentAreaFilled(false);
        btn_d_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_d_pembelianActionPerformed(evt);
            }
        });
        getContentPane().add(btn_d_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 220, 150));

        btn_product.setContentAreaFilled(false);
        btn_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productActionPerformed(evt);
            }
        });
        getContentPane().add(btn_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 90, 60));

        btn_penjualan.setContentAreaFilled(false);
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 90, 60));

        btn_pembelian.setContentAreaFilled(false);
        btn_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelianActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 90, 60));

        btn_preorder.setContentAreaFilled(false);
        btn_preorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preorderActionPerformed(evt);
            }
        });
        getContentPane().add(btn_preorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 90, 60));

        btn_daftar.setContentAreaFilled(false);
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 90, 60));

        btn_catatan.setContentAreaFilled(false);
        btn_catatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_catatanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_catatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 90, 60));

        btn_keluar.setContentAreaFilled(false);
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 90, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_new/daftar (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, 880, 413));

        bar_bawah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Png/bawah.png"))); // NOI18N
        getContentPane().add(bar_bawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, 1000, 90));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/login.gif"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 555));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_d_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_d_pembelianActionPerformed
        // TODO add your handling code here:
        Daftar_Pembelian halamandpembelian = new Daftar_Pembelian();
        halamandpembelian.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_d_pembelianActionPerformed

    private void btn_d_ikanmatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_d_ikanmatiActionPerformed
        // TODO add your handling code here:
        Daftar_Ikanmati halamandikanmati = new Daftar_Ikanmati();
        halamandikanmati.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_d_ikanmatiActionPerformed

    private void btn_d_preorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_d_preorderActionPerformed
        // TODO add your handling code here:
        Daftar_PO halamandpo = new Daftar_PO();
        halamandpo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_d_preorderActionPerformed

    private void btn_d_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_d_penjualanActionPerformed
        // TODO add your handling code here:
        Daftar_Penjualan halamandpenjualan = new Daftar_Penjualan();
        halamandpenjualan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_d_penjualanActionPerformed

    private void btn_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productActionPerformed
        // TODO add your handling code here:
        Timer timer = new Timer(5, null);
        timer.addActionListener(new ActionListener() {
            float opacity = 1.0f;

            public void actionPerformed(ActionEvent e) {
                opacity -= 0.05f;
                if (opacity <= 0.0f) {
                    timer.stop();
                    product halamanproduct = new product();
                    halamanproduct.setVisible(true);
                    dispose(); // Tutup login window setelah fade-out
                } else {
                    setOpacity(opacity); // Kurangi opacity
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_btn_productActionPerformed

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        // TODO add your handling code here:
        Timer timer = new Timer(5, null);
        timer.addActionListener(new ActionListener() {
            float opacity = 1.0f;

            public void actionPerformed(ActionEvent e) {
                opacity -= 0.05f;
                if (opacity <= 0.0f) {
                    timer.stop();
                    Penjualan halamanpenjualan = new Penjualan();
                    halamanpenjualan.setVisible(true);
                    dispose(); // Tutup login window setelah fade-out
                } else {
                    setOpacity(opacity); // Kurangi opacity
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelianActionPerformed
        // TODO add your handling code here:
        Timer timer = new Timer(5, null);
        timer.addActionListener(new ActionListener() {
            float opacity = 1.0f;

            public void actionPerformed(ActionEvent e) {
                opacity -= 0.05f;
                if (opacity <= 0.0f) {
                    timer.stop();
                    Pembelian halamanpembelian = new Pembelian();
                    halamanpembelian.setVisible(true);
                    dispose(); // Tutup login window setelah fade-out
                } else {
                    setOpacity(opacity); // Kurangi opacity
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_btn_pembelianActionPerformed

    private void btn_preorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preorderActionPerformed
        // TODO add your handling code here:
        Timer timer = new Timer(5, null);
        timer.addActionListener(new ActionListener() {
            float opacity = 1.0f;

            public void actionPerformed(ActionEvent e) {
                opacity -= 0.05f;
                if (opacity <= 0.0f) {
                    timer.stop();
                    PreOrder halamanpo = new PreOrder();
                    halamanpo.setVisible(true);
                    dispose(); // Tutup login window setelah fade-out
                } else {
                    setOpacity(opacity); // Kurangi opacity
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_btn_preorderActionPerformed

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // TODO add your handling code here:
        Timer timer = new Timer(20, null);
        timer.addActionListener(new ActionListener() {
            float opacity = 1.0f;

            public void actionPerformed(ActionEvent e) {
                opacity -= 0.05f;
                if (opacity <= 0.0f) {
                    timer.stop();
                    Daftar halamandaftar = new Daftar();
                    halamandaftar.setVisible(true);
                    dispose(); // Tutup login window setelah fade-out
                } else {
                    setOpacity(opacity); // Kurangi opacity
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_btn_daftarActionPerformed

    private void btn_catatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_catatanActionPerformed
        // TODO add your handling code here:
        Timer timer = new Timer(20, null);
        timer.addActionListener(new ActionListener() {
            float opacity = 1.0f;

            public void actionPerformed(ActionEvent e) {
                opacity -= 0.05f;
                if (opacity <= 0.0f) {
                    timer.stop();
                    Catatan halamancatatan = new Catatan();
                    halamancatatan.setVisible(true);
                    dispose(); // Tutup login window setelah fade-out
                } else {
                    setOpacity(opacity); // Kurangi opacity
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_btn_catatanActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "apakah anda yakin ingin keluar?","PERINGATAN",dialogBtn);

        if(dialogResult == 0) {
            Login n = new Login();
            n.setVisible(true);
            this.dispose();
        }else{

        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bar_bawah;
    private javax.swing.JButton btn_catatan;
    private javax.swing.JButton btn_d_ikanmati;
    private javax.swing.JButton btn_d_pembelian;
    private javax.swing.JButton btn_d_penjualan;
    private javax.swing.JButton btn_d_preorder;
    private javax.swing.JButton btn_daftar;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_preorder;
    private javax.swing.JButton btn_product;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
