/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import com.sun.jdi.connect.spi.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author haisb
 */
public class Ganti_password extends javax.swing.JFrame {

    /**
     * Creates new form Rfid
     */
    public Ganti_password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_password_baru = new javax.swing.JTextField();
        txt_password_lama = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_password_baru.setBorder(null);
        getContentPane().add(txt_password_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 158, 210, 20));

        txt_password_lama.setBorder(null);
        getContentPane().add(txt_password_lama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 20));

        btn_simpan.setContentAreaFilled(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Png/Password.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Png/simpan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 245, 54, 55));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:

        String passwordLama = txt_password_lama.getText().trim();
    String passwordBaru = txt_password_baru.getText().trim();

    if (passwordLama.isEmpty() || passwordBaru.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password lama dan baru tidak boleh kosong!");
        return;
    }

    try {
//        Connection conn = Config.configDB(); // Koneksi ke database
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/didiexs", "root", "");

        // Cek apakah password lama cocok
        String sqlCek = "SELECT id FROM akun WHERE password = ?";
        java.sql.PreparedStatement pstCek = conn.prepareStatement(sqlCek);
        pstCek.setString(1, passwordLama);
        java.sql.ResultSet rs = pstCek.executeQuery();

        if (rs.next()) {
            int id = rs.getInt("id");

            // Update password
            String sqlUpdate = "UPDATE akun SET password = ? WHERE id = ?";
            java.sql.PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
            pstUpdate.setString(1, passwordBaru);
            pstUpdate.setInt(2, id);
            pstUpdate.executeUpdate();

            JOptionPane.showMessageDialog(this, "Password berhasil diperbarui!");
        } else {
            JOptionPane.showMessageDialog(this, "Password lama salah!");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ganti_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ganti_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ganti_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ganti_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ganti_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_password_baru;
    private javax.swing.JTextField txt_password_lama;
    // End of variables declaration//GEN-END:variables
}
