package App;

import Class.Session;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Login extends javax.swing.JFrame {

    public Login() {
        setUndecorated(true);
        System.setProperty("sun.java2d.opengl", "true");
        initComponents();

        txt_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String input = txt_Username.getText();
                if (input.length() >= 10) { // Panjang UID RFID, sesuaikan
                    loginWithRFID(input);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Username = new javax.swing.JTextField();
        txt_Password = new javax.swing.JPasswordField();
        btn_password = new javax.swing.JButton();
        btn_rfid = new javax.swing.JButton();
        btn_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        login_svg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Username.setBorder(null);
        txt_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 250, 40));

        txt_Password.setBorder(null);
        txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 250, 40));

        btn_password.setContentAreaFilled(false);
        btn_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 180, 70));

        btn_rfid.setContentAreaFilled(false);
        btn_rfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rfidActionPerformed(evt);
            }
        });
        getContentPane().add(btn_rfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 190, 60));

        btn_Login.setContentAreaFilled(false);
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 300, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Png/loginn.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 342, 473));

        login_svg.setIcon(new FlatSVGIcon("UI_Svg/loginn.svg"));
        getContentPane().add(login_svg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 555));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsernameActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "SELECT id FROM akun WHERE user = ? AND password = ?";
            Connection conn = Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txt_Username.getText());
            pst.setString(2, new String(txt_Password.getPassword()));

            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int idAkun = rs.getInt("id");
                Session.setIdAkun(idAkun);
                JOptionPane.showMessageDialog(null, "BERHASIL LOGIN");

                // Mulai fade-out sebelum buka Dashboard
                Timer timer = new Timer(20, null);
                timer.addActionListener(new ActionListener() {
                    float opacity = 1.0f;

                    public void actionPerformed(ActionEvent e) {
                        opacity -= 0.05f;
                        if (opacity <= 0.0f) {
                            timer.stop();
                            Dashboard dashboard = new Dashboard();
                            dashboard.setVisible(true);
                            dispose(); // Tutup login window setelah fade-out
                        } else {
                            setOpacity(opacity); // Kurangi opacity
                        }
                    }
                });
                timer.start();

            } else {
                JOptionPane.showMessageDialog(null, "USERNAME ATAU PASSWORD SALAH");
            }

            rs.close();
            pst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }

    }//GEN-LAST:event_btn_LoginActionPerformed

    private void loginWithRFID(String rfidUid) {
        try {
            String sql = "SELECT id FROM akun WHERE rfid = ?";
            Connection conn = Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, rfidUid);

            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int idAkun = rs.getInt("id");
                Session.setIdAkun(idAkun);

                Dashboard dasboard = new Dashboard();
                dasboard.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "RFID TIDAK DITEMUKAN");
            }

            rs.close();
            pst.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordActionPerformed

    private void btn_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passwordActionPerformed
        // TODO add your handling code here:

        Ganti_password ganti_password = new Ganti_password();
        ganti_password.setVisible(true);
        ganti_password.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_btn_passwordActionPerformed

    private void btn_rfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rfidActionPerformed
        // TODO add your handling code here:

        Rfid rfid = new Rfid();
        rfid.setVisible(true);
        rfid.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        

    }//GEN-LAST:event_btn_rfidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_password;
    private javax.swing.JButton btn_rfid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel login_svg;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
