
package App;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class product_edit extends javax.swing.JFrame {

    private product parent;
    private int id;
    private String nama;
    private int stok;
    private double harga;
    
    public product_edit(product parent, int id, String nama, int stok, double harga) {
        initComponents();
        setLocationRelativeTo(null);

        this.parent = parent;
        this.id = id;
        this.nama = nama;
        this.stok = stok;
        this.harga = harga;

        txt_ID.setText(String.valueOf(id)); // Pastikan ada field txtId jika ingin menampilkan id
        txt_nama.setText(nama);
        txt_stok.setText(String.valueOf(stok));
        txt_harga.setText(String.format("%.2f", harga)); // Menampilkan dua angka di belakang koma

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

//        // Buat txt_ID tidak bisa diubah
//        txt_ID.setEditable(false); // Tidak bisa diketik, tapi tetap terlihat
//        // txt_ID.setEnabled(false); // Opsional: Membuat tampilan abu-abu
//        txt_ID.setFocusable(false); // Tidak bisa dipilih dengan kursor
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_stok = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_Edit = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_stok.setBorder(null);
        getContentPane().add(txt_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 123, 210, 20));

        txt_harga.setBorder(null);
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 178, 210, 20));

        txt_nama.setBorder(null);
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 68, 210, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Png/edit.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 244, 54, 55));

        btn_Edit.setContentAreaFilled(false);
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, 80));

        background.setIcon(new FlatSVGIcon("UI_Svg/btn_Edit.svg"));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 340));

        txt_ID.setVisible(false);
        txt_ID.setText("jTextField1");
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        // TODO add your handling code here:

        String namaBaru = txt_nama.getText();
        int stokBaru = Integer.parseInt(txt_stok.getText());

        // Pastikan angka desimal memiliki format yang benar
        String hargaText = txt_harga.getText().replace(",", ".");
        double hargaBaru = Double.parseDouble(hargaText);

        // Validasi data (opsional, untuk memastikan input tidak kosong)
        if (namaBaru.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
            return;
        }

        // Query untuk update data berdasarkan ID
        String query = "UPDATE products SET jenis=?, stok=?, harga=? WHERE id=?";

        try {
            java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/didiexs", "root", "");
            java.sql.PreparedStatement pst = conn.prepareStatement(query);

            // Set parameter query
            pst.setString(1, namaBaru);
            pst.setInt(2, stokBaru);
            pst.setDouble(3, hargaBaru);
            pst.setInt(4, id); // Gunakan idProduk yang sudah dideklarasikan sebelumnya

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

                // Refresh tabel utama di ManajemenProducts
                parent.loadData();

                // Tutup jendela edit setelah penyimpanan sukses
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data!");
            }

            // Tutup koneksi
            pst.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BtnEdit().setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new product_edit().setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BtnEdit().setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new product_edit().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_stok;
    // End of variables declaration//GEN-END:variables
}
